### ISSUE TITLE
nfmd.predict method seems to don't work properly

### ISSUE THREAD

**Issue by npaj** [sheadan/NFMD-ExtractionInstantaneous#2]
Dear E. Shea Daniel, 

The nfmd.predict method seems to have a shape problem at NFMD.py#L357 .
<img width="935" alt="Capture d’écran 2022-07-15 à 11 43 50" src="https://user-images.githubusercontent.com/45687891/179198477-75cc9e44-4afa-4513-84d6-a308f1a3bd34.png">

Also, the loss variable is not detached at NFMD.py#L336 which leads to an error in NFMD.py#L128 (probably caused by new version of PyTorch) .

Thank you very much for this work !
Best
Nicolas

**Comment by sheadan** [comment]
Hi Nicolas,

Thanks for writing in! I will work on updating the code for the most recent version of Pytorch.

Regarding your error, is this error from one of the example notebooks or one of your own notebooks? If it is one of your notebooks, what is the shape of your array Nt?

Thanks!
Dan

**Comment by sheadan** [comment]
@npaj thanks for the suggestion on putting detach statement on L337 for loss variable. This issue has been addressed and a Dockerfile and Docker compose spec have been added to the repository.

Have you solved the issue you posted about above? The first thing that comes to mind is the Nt array is an Nx2 matrix rather than a vector?  If you haven't solved the problem, perhaps you can post a minimum working example of the error?

Thanks!
Dan

**Comment by sheadan** [comment]
Closing issue due to no response

**Comment by npaj** [comment]
Hi @sheadan, 

The problem was the matrix size as you explained. 
I used int as it is given in the doc string ([here](https://github.com/sheadan/NFMD-ExtractionInstantaneous/blob/cce3bd61732c1299e2a1c36ec2a6181282586d8d/nfmd/NFMD.py#L346 )) and it was not.
So everything is fixed.
Thanks again for this work !
